const { kebabCase } = require("./utils");

function styleExtension(cssMode) {
  if (cssMode === "scss") return "scss";
  if (cssMode === "less") return "less";
  return "css";
}

function tokenReference(tokenPath, cssMode) {
  const key = kebabCase(tokenPath.replace(/\./g, "-"));
  if (cssMode === "scss") return "$" + key;
  if (cssMode === "less") return "@" + key;
  return "var(--" + key + ")";
}

function pageStyles(plan, cssMode, pageVariant) {
  const ext = styleExtension(cssMode);
  const background = tokenReference("color.bg", cssMode);
  const surface = tokenReference("color.surface", cssMode);
  const border = tokenReference("color.border", cssMode);
  const textPrimary = tokenReference("color.text.primary", cssMode);
  const textSecondary = tokenReference("color.text.secondary", cssMode);
  const textMuted = tokenReference("color.text.muted", cssMode);
  const brandPrimary = tokenReference("color.brand.primary", cssMode);
  const brandAccent = tokenReference("color.brand.accent", cssMode);
  const spaceSm = tokenReference("space.sm", cssMode);
  const spaceMd = tokenReference("space.md", cssMode);
  const spaceLg = tokenReference("space.lg", cssMode);
  const spaceXl = tokenReference("space.xl", cssMode);
  const spaceSection = tokenReference("space.section", cssMode);
  const radiusSm = tokenReference("radius.sm", cssMode);
  const radiusMd = tokenReference("radius.md", cssMode);
  const radiusLg = tokenReference("radius.lg", cssMode);
  const radiusPill = tokenReference("radius.pill", cssMode);
  const shadowCard = tokenReference("shadow.card", cssMode);
  const container = tokenReference("layout.container", cssMode);
  const gridGap = tokenReference("layout.gridGap", cssMode);
  const titleSize = tokenReference("typography.title.size", cssMode);
  const titleLineHeight = tokenReference("typography.title.lineHeight", cssMode);
  const titleWeight = tokenReference("typography.title.weight", cssMode);
  const bodySize = tokenReference("typography.body.size", cssMode);
  const bodyLineHeight = tokenReference("typography.body.lineHeight", cssMode);
  const bodyWeight = tokenReference("typography.body.weight", cssMode);
  const labelSize = tokenReference("typography.label.size", cssMode);
  const labelLineHeight = tokenReference("typography.label.lineHeight", cssMode);
  const labelWeight = tokenReference("typography.label.weight", cssMode);
  if (plan.fidelityMode === "pixel-perfect") {
    return [
      ext === "css" ? '@import "./tokens.css";' : `@import "./tokens.${ext}";`,
      "",
      "*, *::before, *::after {",
      "  box-sizing: border-box;",
      "}",
      "",
      "html, body {",
      "  margin: 0;",
      "  min-height: 100%;",
      "}",
      "",
      "body {",
      `  background: ${background};`,
      `  color: ${textPrimary};`,
      "}",
      "",
      "button, input, textarea, select {",
      "  font: inherit;",
      "}",
      "",
      "img, svg {",
      "  display: block;",
      "}",
      "",
      ".page-shell {",
      "  position: relative;",
      "  min-height: 100vh;",
      `  background: ${background};`,
      "}",
      "",
      ".page-main {",
      "  position: relative;",
      "}",
      "",
      "/* Exact visual properties are emitted below from measured overrides. */",
    ].join("\n");
  }
  return [
    ext === "css" ? '@import "./tokens.css";' : `@import "./tokens.${ext}";`,
    "",
    "*, *::before, *::after {",
    "  box-sizing: border-box;",
    "}",
    "",
    "body {",
    "  margin: 0;",
    "  font-family: 'PingFang SC', 'Microsoft YaHei', 'Noto Sans SC', 'Segoe UI', sans-serif;",
    `  background: ${background};`,
    `  color: ${textPrimary};`,
    `  font-size: ${bodySize};`,
    `  line-height: ${bodyLineHeight};`,
    `  font-weight: ${bodyWeight};`,
    "}",
    "",
    ".page-shell {",
    `  min-height: 100vh;`,
    `  background: ${background};`,
    "}",
    "",
    ".page-shell--workspace {",
    "  position: relative;",
    "  overflow: hidden;",
    "  min-height: 100dvh;",
    "}",
    "",
    ".page-shell--workspace::before {",
    "  content: '';",
    "  position: absolute;",
    "  inset: 0 0 auto 0;",
    "  height: 118px;",
    "  background: linear-gradient(90deg, rgba(212, 233, 250, 0.78), rgba(225, 244, 233, 0.72), rgba(255, 255, 255, 0));",
    "  pointer-events: none;",
    "}",
    "",
    ".page-main {",
    `  width: min(${container}, calc(100% - 48px));`,
    "  margin: 0 auto;",
    "  display: grid;",
    `  gap: ${spaceSection};`,
    `  padding: ${spaceXl} 0 calc(${spaceSection} - ${spaceMd});`,
    "}",
    "",
    ".page-main--workspace {",
    "  position: relative;",
    "  width: calc(100% - 28px);",
    "  max-width: none;",
    "  gap: 12px;",
    "  padding: 14px 0 18px;",
    "  align-items: start;",
    "  min-height: calc(100dvh - 14px);",
    "}",
    "",
    ".section-shell {",
    "  display: grid;",
    `  gap: ${gridGap};`,
    `  padding: ${spaceXl};`,
    `  border: 1px solid ${border};`,
    `  border-radius: ${radiusLg};`,
    `  background: ${surface};`,
    `  box-shadow: ${shadowCard};`,
    "}",
    "",
    ".section-shell__header {",
    "  display: grid;",
    `  gap: ${spaceSm};`,
    "}",
    "",
    ".section-shell__body {",
    "  display: grid;",
    `  gap: ${gridGap};`,
    "}",
    "",
    ".section-shell__body--two-column {",
    "  grid-template-columns: minmax(0, 1.2fr) minmax(280px, 0.8fr);",
    "  align-items: start;",
    "}",
    "",
    ".section-shell__body--stack {",
    "  grid-template-columns: minmax(0, 1fr);",
    "}",
    "",
    ".section-shell__lead, .section-shell__aside, .section-grid, .section-rail {",
    "  display: grid;",
    `  gap: ${gridGap};`,
    "}",
    "",
    ".section-shell__aside {",
    `  padding: ${spaceLg};`,
    `  border: 1px solid ${border};`,
    `  border-radius: ${radiusLg};`,
    "  background: color-mix(in srgb, white 78%, transparent);",
    "}",
    "",
    ".section-grid--card-grid {",
    "  grid-template-columns: repeat(3, minmax(0, 1fr));",
    "}",
    "",
    ".section-grid--accordion-list {",
    "  grid-template-columns: minmax(0, 1fr);",
    `  gap: ${spaceMd};`,
    "}",
    "",
    ".section-rail {",
    "  grid-auto-flow: column;",
    "  grid-auto-columns: minmax(280px, 1fr);",
    "  overflow-x: auto;",
    `  padding-bottom: ${spaceSm};`,
    "}",
    "",
    ".section-shell__role {",
    "  margin: 0;",
    `  color: ${textMuted};`,
    `  font-size: ${labelSize};`,
    `  line-height: ${labelLineHeight};`,
    `  font-weight: ${labelWeight};`,
    "}",
    "",
    ".section-shell h2, .component-shell h3 {",
    "  margin: 0;",
    `  color: ${textPrimary};`,
    `  font-size: ${titleSize};`,
    `  line-height: ${titleLineHeight};`,
    `  font-weight: ${titleWeight};`,
    "}",
    "",
    ".section-shell p, .component-shell p {",
    "  margin: 0;",
    `  color: ${textSecondary};`,
    `  font-size: ${bodySize};`,
    `  line-height: ${bodyLineHeight};`,
    `  font-weight: ${bodyWeight};`,
    "}",
    "",
    ".component-shell {",
    "  display: grid;",
    `  gap: ${spaceMd};`,
    `  border: 1px solid ${border};`,
    `  border-radius: ${radiusMd};`,
    `  padding: ${spaceLg};`,
    `  background: ${surface};`,
    `  box-shadow: ${shadowCard};`,
    "}",
    "",
    ".component-shell--accent {",
    `  border-color: ${brandPrimary};`,
    "}",
    "",
    ".button-shell {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    `  min-height: calc(${spaceXl} + ${spaceSm});`,
    `  padding: ${spaceSm} ${spaceLg};`,
    `  border-radius: ${radiusPill};`,
    `  background: linear-gradient(135deg, ${brandPrimary}, ${brandAccent});`,
    "  color: white;",
    "}",
    "",
    ".workspace-topbar {",
    "  position: relative;",
    "  z-index: 1;",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: space-between;",
    "  min-height: 32px;",
    "  padding: 2px 8px 0 2px;",
    "}",
    "",
    ".workspace-topbar__left {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 10px;",
    "}",
    "",
    ".workspace-topbar__cluster {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 10px;",
    "  min-width: 0;",
    "}",
    "",
    ".workspace-icon-chip {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  width: 28px;",
    "  height: 28px;",
    `  border: 1px solid ${border};`,
    `  border-radius: ${radiusSm};`,
    "  background: rgba(255, 255, 255, 0.9);",
    "  color: #475569;",
    "  box-shadow: 0 2px 10px rgba(15, 23, 42, 0.04);",
    "}",
    "",
    ".workspace-icon-chip--back {",
    "  position: relative;",
    "  color: transparent;",
    "}",
    "",
    ".workspace-icon-chip--back::before {",
    "  content: '';",
    "  width: 8px;",
    "  height: 8px;",
    "  border-left: 1.8px solid #667085;",
    "  border-bottom: 1.8px solid #667085;",
    "  transform: rotate(45deg) translate(1px, -1px);",
    "}",
    "",
    ".workspace-brand-mark {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  width: 26px;",
    "  height: 26px;",
    "  border-radius: 8px;",
    `  background: linear-gradient(135deg, ${brandPrimary}, #16c7b7);`,
    "  color: white;",
    "  font-size: 14px;",
    "  font-weight: 700;",
    "}",
    "",
    ".workspace-brand-mark::before {",
    "  content: '✦';",
    "}",
    "",
    ".workspace-topbar__brand {",
    "  font-size: 14px;",
    "  font-weight: 700;",
    `  color: ${textPrimary};`,
    "}",
    "",
    ".workspace-breadcrumbs {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 6px;",
    "  white-space: nowrap;",
    "  color: #94a3b8;",
    "  font-size: 12px;",
    "}",
    "",
    ".workspace-breadcrumbs__primary {",
    `  color: ${textSecondary};`,
    "  font-weight: 500;",
    "}",
    "",
    ".workspace-breadcrumbs__sep {",
    `  color: ${textMuted};`,
    "}",
    "",
    ".workspace-breadcrumbs span:last-child {",
    "  color: #a7b3c5;",
    "}",
    "",
    ".workspace-shell {",
    "  position: relative;",
    "  z-index: 1;",
    "  display: grid;",
    "  grid-template-columns: minmax(0, 1fr) 516px;",
    "  gap: 12px;",
    "  align-items: stretch;",
    "  min-height: calc(100dvh - 74px);",
    "}",
    "",
    ".workspace-preview {",
    `  border: 1px solid ${border};`,
    "  border-radius: 17px;",
    "  background: linear-gradient(180deg, rgba(255, 255, 255, 0.99), rgba(247, 250, 253, 0.96));",
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,0.7);",
    "  min-height: calc(100dvh - 88px);",
    "  overflow: hidden;",
    "  padding: 0;",
    "}",
    "",
    ".workspace-canvas {",
    "  height: 100%;",
    "  min-height: calc(100dvh - 112px);",
    "  border: 0;",
    "  border-radius: 17px;",
    "  background: linear-gradient(180deg, rgba(255, 255, 255, 0.99), rgba(248, 250, 252, 0.95));",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "}",
    "",
    ".workspace-empty {",
    "  display: grid;",
    "  justify-items: center;",
    "  gap: 10px;",
    "  text-align: center;",
    "}",
    "",
    ".workspace-empty__illustration {",
    "  width: 96px;",
    "  height: 76px;",
    "  border-radius: 20px;",
    "  border: 1.5px dashed rgba(148, 163, 184, 0.62);",
    "  background: linear-gradient(180deg, rgba(255,255,255,0.96), rgba(249,250,251,0.86));",
    "  position: relative;",
    "}",
    "",
    ".workspace-empty__illustration::before {",
    "  content: '';",
    "  position: absolute;",
    "  left: 50%;",
    "  top: 50%;",
    "  width: 40px;",
    "  height: 28px;",
    "  transform: translate(-50%, -35%);",
    "  border: 2px solid rgba(107, 114, 128, 0.56);",
    "  border-radius: 8px;",
    "}",
    "",
    ".workspace-empty__illustration::after {",
    "  content: '';",
    "  position: absolute;",
    "  left: 50%;",
    "  top: 21px;",
    "  width: 16px;",
    "  height: 16px;",
    "  transform: translateX(-50%);",
    "  border-radius: 50%;",
    "  border: 2px solid rgba(107, 114, 128, 0.48);",
    "  background: white;",
    "}",
    "",
    ".workspace-empty__title {",
    "  margin: 0;",
    "  font-size: 16px;",
    "  font-weight: 500;",
    "  color: #4b5563;",
    "}",
    "",
    ".workspace-empty__hint {",
    "  margin: 0;",
    "  font-size: 12px;",
    "  color: #a0aec0;",
    "}",
    "",
    ".workspace-empty__hint a {",
    `  color: ${brandPrimary};`,
    "  text-decoration: none;",
    "}",
    "",
    ".workspace-sidebar {",
    "  min-height: calc(100dvh - 88px);",
    "}",
    "",
    ".workspace-panel {",
    "  min-height: 100%;",
    `  border: 1px solid ${border};`,
    "  border-radius: 16px;",
    "  background: rgba(255, 255, 255, 0.92);",
    "  box-shadow: 0 8px 22px rgba(15, 23, 42, 0.035);",
    "  padding: 14px 16px 14px;",
    "  display: flex;",
    "  flex-direction: column;",
    "  gap: 18px;",
    "}",
    "",
    ".workspace-panel__header {",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: space-between;",
    "}",
    "",
    ".workspace-panel__block {",
    "  display: grid;",
    "  gap: 14px;",
    "}",
    "",
    ".workspace-panel__block + .workspace-panel__block {",
    "  padding-top: 2px;",
    "}",

    ".workspace-panel__block--generation {",
    "  flex: 1 1 auto;",
    "  display: flex;",
    "  flex-direction: column;",
    "  align-content: start;",
    "  gap: 12px;",
    "}",
    "",
    ".workspace-panel__title {",
    "  margin: 0;",
    "  font-size: 13px;",
    "  font-weight: 700;",
    "  color: #111827;",
    "}",
    "",
    ".workspace-panel__ornament {",
    "  width: 34px;",
    "  height: 34px;",
    "  border-radius: 50%;",
    "  border: 1px solid rgba(198, 218, 242, 0.92);",
    "  background: linear-gradient(135deg, rgba(220, 239, 255, 0.96), rgba(241, 228, 255, 0.88));",
    "  position: relative;",
    "  flex: 0 0 auto;",
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,0.75);",
    "}",
    "",
    ".workspace-panel__ornament::before, .workspace-panel__ornament::after {",
    "  content: '';",
    "  position: absolute;",
    "  inset: 9px;",
    "  border: 1.8px solid rgba(17, 24, 39, 0.88);",
    "  border-radius: 50%;",
    "}",
    "",
    ".workspace-panel__ornament::after {",
    "  inset: 6px 15px 15px 6px;",
    "  border-width: 1.8px 1.8px 0 0;",
    "  border-radius: 0 10px 0 0;",
    "  transform: rotate(45deg);",
    "}",
    "",
    ".workspace-fields {",
    "  display: grid;",
    "  gap: 14px;",
    "}",
    "",
    ".workspace-fields--two-column {",
    "  grid-template-columns: repeat(2, minmax(0, 1fr));",
    "  column-gap: 16px;",
    "  row-gap: 14px;",
    "}",

    ".workspace-fields--info {",
    "  gap: 14px;",
    "}",

    ".workspace-info-row {",
    "  display: grid;",
    "  grid-template-columns: repeat(2, minmax(0, 1fr));",
    "  gap: 16px;",
    "}",
    "",
    ".workspace-field {",
    "  display: grid;",
    "  gap: 7px;",
    "}",
    "",
    ".workspace-field--full {",
    "  grid-column: 1 / -1;",
    "}",
    "",
    ".workspace-field__label {",
    "  font-size: 11.5px;",
    "  font-weight: 500;",
    "  color: #1f2937;",
    "}",

    ".workspace-field__required {",
    "  color: #ef4444;",
    "  margin-right: 4px;",
    "}",
    "",
    ".workspace-input, .workspace-select, .workspace-mini-select {",
    "  min-height: 38px;",
    "  display: flex;",
    "  align-items: center;",
    "  padding: 0 12px;",
    `  border: 1px solid ${border};`,
    `  border-radius: ${radiusSm};`,
    "  background: white;",
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,0.7), 0 1px 1px rgba(15, 23, 42, 0.015);",
    "  color: #c2cad7;",
    "  font-size: 11.5px;",
    "}",
    "",
    ".workspace-mini-select {",
    "  justify-content: center;",
    "  color: #7d8798;",
    "}",
    "",
    ".workspace-segmented {",
    "  display: grid;",
    "  grid-template-columns: repeat(2, minmax(0, 1fr));",
    `  border: 1px solid ${border};`,
    `  border-radius: ${radiusSm};`,
    "  padding: 3px;",
    "  background: white;",
    "}",
    "",
    ".workspace-segmented__item {",
    "  min-height: 34px;",
    "  border: 0;",
    "  background: transparent;",
    `  border-radius: ${radiusSm};`,
    "  color: #3d4a5c;",
    "  font-size: 12px;",
    "  font-weight: 500;",
    "}",
    "",
    ".workspace-segmented__item.is-active {",
    `  background: ${brandPrimary};`,
    "  color: white;",
    "}",

    ".workspace-select::after {",
    "  content: '';",
    "  width: 6px;",
    "  height: 6px;",
    "  border-right: 1.5px solid #9aa4b2;",
    "  border-bottom: 1.5px solid #9aa4b2;",
    "  transform: rotate(45deg) translateY(-1px);",
    "  margin-left: auto;",
    "}",
    "",
    ".workspace-textarea {",
    "  min-height: clamp(186px, 26vh, 220px);",
    `  border: 1px solid ${border};`,
    `  border-radius: ${radiusSm};`,
    "  background: white;",
    "  padding: 10px 12px;",
    "  display: grid;",
    "  grid-template-rows: auto 1fr auto;",
    "  align-content: start;",
    "  gap: 10px;",
    `  color: ${textMuted};`,
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,0.7);",
    "}",
    "",
    ".workspace-upload-row {",
    "  display: flex;",
    "  align-items: flex-start;",
    "  gap: 10px;",
    "}",
    "",
    ".workspace-upload-chip {",
    "  width: 40px;",
    "  height: 40px;",
    `  border: 1px solid ${border};`,
    `  border-radius: ${radiusSm};`,
    "  background: #f8fafc;",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  font-size: 18px;",
    `  color: ${textSecondary};`,
    "}",
    "",
    ".workspace-textarea__placeholder {",
    "  margin: 2px 0 0;",
    "  font-size: 12px;",
    `  color: #c9d1dc;`,
    "}",
    "",
    ".workspace-textarea__spacer {",
    "  min-height: 64px;",
    "}",
    "",
    ".workspace-chip {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  gap: 6px;",
    "  width: fit-content;",
    `  padding: 4px 10px;`,
    `  border: 1px solid ${border};`,
    "  border-radius: 999px;",
    "  background: rgba(255,255,255,0.92);",
    `  color: ${textSecondary};`,
    "  font-size: 11.5px;",
    "}",
    "",
    ".workspace-chip--optimize {",
    "  justify-self: start;",
    "  padding: 4px 8px;",
    "  border-color: rgba(51, 199, 106, 0.16);",
    "  background: rgba(51, 199, 106, 0.06);",
    "  color: #24b05a;",
    "  font-weight: 500;",
    "}",
    "",
    ".workspace-chip__spark {",
    "  font-size: 10px;",
    "  line-height: 1;",
    "}",
    "",
    ".workspace-toolbar {",
    "  margin-top: auto;",
    "  display: grid;",
    "  grid-template-columns: minmax(0, 1fr) 60px 70px;",
    "  gap: 8px;",
    "}",

    ".workspace-toolbar .workspace-select, .workspace-toolbar .workspace-mini-select {",
    "  min-height: 30px;",
    "  padding: 0 10px;",
    `  border: 1px solid ${border};`,
    "  border-radius: 8px;",
    "  background: #ffffff;",
    "  box-shadow: none;",
    "  color: #7d8798;",
    "  font-size: 11.5px;",
    "}",
    "",
    ".workspace-primary-action {",
    "  min-height: 38px;",
    "  width: 100%;",
    "  border: 0;",
    "  border-radius: 9px;",
    `  background: linear-gradient(90deg, ${brandPrimary}, ${brandAccent});`,
    "  color: white;",
    "  font-size: 14px;",
    "  font-weight: 600;",
    "  margin-top: 10px;",
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,0.25);",
    "}",
    "",
    "@media (max-width: 1600px) {",
    "  .workspace-shell {",
    "    grid-template-columns: minmax(0, 1fr) 468px;",
    "  }",
    "}",
    "",
    "@media (max-width: 1280px) {",
    "  .workspace-shell {",
    "    grid-template-columns: minmax(0, 1fr) 414px;",
    "    min-height: calc(100dvh - 72px);",
    "  }",
    "",
    "  .workspace-preview, .workspace-sidebar {",
    "    min-height: calc(100dvh - 86px);",
    "  }",
    "",
    "  .workspace-canvas {",
    "    min-height: calc(100dvh - 108px);",
    "  }",
    "}",
    "",
    "@media (max-width: 1024px) {",
    "  .section-grid--card-grid {",
    "    grid-template-columns: repeat(2, minmax(0, 1fr));",
    "  }",
    "",
    "  .workspace-shell {",
    "    grid-template-columns: minmax(0, 1fr) 348px;",
    "    min-height: calc(100dvh - 70px);",
    "  }",
    "",
    "  .workspace-fields--two-column,",
    "  .workspace-info-row {",
    "    grid-template-columns: minmax(0, 1fr);",
    "  }",
    "}",
    "",
    "@media (max-width: 900px) {",
    "  .page-main--workspace {",
    "    width: calc(100% - 18px);",
    "    min-height: auto;",
    "  }",
    "",
    "  .workspace-topbar {",
    "    padding-top: 4px;",
    "  }",
    "",
    "  .workspace-topbar__left {",
    "    flex-wrap: wrap;",
    "    row-gap: 6px;",
    "  }",
    "",
    "  .workspace-topbar__cluster {",
    "    flex-wrap: wrap;",
    "    row-gap: 4px;",
    "  }",
    "",
    "  .workspace-shell {",
    "    grid-template-columns: minmax(0, 1fr);",
    "    min-height: auto;",
    "  }",
    "",
    "  .workspace-preview, .workspace-sidebar {",
    "    min-height: auto;",
    "  }",
    "",
    "  .workspace-canvas {",
    "    min-height: 340px;",
    "  }",
    "}",
    "",
    "@media (max-width: 768px) {",
    "  .page-main {",
    "    width: min(100% - 32px, 100%);",
    `    gap: ${spaceXl};`,
    "  }",
    "",
    "  .section-shell {",
    `    padding: ${spaceLg};`,
    "  }",
    "",
    "  .section-shell__body--two-column,",
    "  .section-grid--card-grid {",
    "    grid-template-columns: minmax(0, 1fr);",
    "  }",
    "",
    "  .section-rail {",
    "    grid-auto-columns: minmax(85%, 1fr);",
    "  }",
    "",
    "  .page-main--workspace {",
    "    width: calc(100% - 16px);",
    "    gap: 10px;",
    "  }",
    "",
    "  .workspace-topbar {",
    "    gap: 8px;",
    "  }",
    "",
    "  .workspace-breadcrumbs {",
    "    white-space: normal;",
    "  }",
    "",
    "  .workspace-preview {",
    "    padding: 12px;",
    "  }",
    "",
    "  .workspace-panel {",
    "    padding: 10px;",
    "  }",
    "",
    "  .workspace-toolbar {",
    "    grid-template-columns: minmax(0, 1fr) 72px 72px;",
    "  }",
    "}",
    "",
    "@media (max-width: 560px) {",
    "  .workspace-topbar__cluster {",
    "    gap: 6px;",
    "  }",
    "",
    "  .workspace-topbar__brand {",
    "    font-size: 13px;",
    "  }",
    "",
    "  .workspace-breadcrumbs {",
    "    font-size: 11px;",
    "  }",
    "",
    "  .workspace-canvas {",
    "    min-height: 280px;",
    "  }",
    "",
    "  .workspace-empty__title {",
    "    font-size: 15px;",
    "  }",
    "",
    "  .workspace-toolbar {",
    "    grid-template-columns: minmax(0, 1fr);",
    "  }",
    "",
    "  .workspace-segmented {",
    "    grid-template-columns: minmax(0, 1fr);",
    "  }",
    "",
    "  .workspace-upload-row {",
    "    flex-direction: column;",
    "  }",
    "}",
    ].join("\n");
}

function styleProperties(styles) {
  if (!styles) return "";
  const props = [];
  const map = {
    padding: "padding",
    margin: "margin",
    gap: "gap",
    backgroundColor: "background",
    color: "color",
    borderColor: "border-color",
    borderRadius: "border-radius",
    fontSize: "font-size",
    lineHeight: "line-height",
    fontWeight: "font-weight",
    fontFamily: "font-family",
    fontStyle: "font-style",
    letterSpacing: "letter-spacing",
    textAlign: "text-align",
    textTransform: "text-transform",
    whiteSpace: "white-space",
    maxWidth: "max-width",
    minWidth: "min-width",
    maxHeight: "max-height",
    minHeight: "min-height",
    width: "width",
    height: "height",
    boxShadow: "box-shadow",
    border: "border",
    display: "display",
    alignItems: "align-items",
    justifyContent: "justify-content",
    flexDirection: "flex-direction",
    flexWrap: "flex-wrap",
    flex: "flex",
    gridTemplateColumns: "grid-template-columns",
    gridTemplateRows: "grid-template-rows",
    gridAutoFlow: "grid-auto-flow",
    gridColumn: "grid-column",
    gridRow: "grid-row",
    position: "position",
    inset: "inset",
    top: "top",
    right: "right",
    bottom: "bottom",
    left: "left",
    overflow: "overflow",
    overflowX: "overflow-x",
    overflowY: "overflow-y",
    opacity: "opacity",
    zIndex: "z-index",
    transform: "transform",
    objectFit: "object-fit",
    objectPosition: "object-position",
    borderTop: "border-top",
    borderRight: "border-right",
    borderBottom: "border-bottom",
    borderLeft: "border-left",
    paddingTop: "padding-top",
    paddingRight: "padding-right",
    paddingBottom: "padding-bottom",
    paddingLeft: "padding-left",
    marginTop: "margin-top",
    marginRight: "margin-right",
    marginBottom: "margin-bottom",
    marginLeft: "margin-left",
  };
  for (const [key, cssProp] of Object.entries(map)) {
    if (styles[key] !== undefined) {
      props.push(`  ${cssProp}: ${styles[key]};`);
    }
  }
  return props.join("\n");
}

function renderPreciseOverrides(overrides) {
  if (!overrides || Object.keys(overrides).length === 0) return "";
  const blocks = [];

  if (overrides.pageShell && Object.keys(overrides.pageShell).length > 0) {
    const props = styleProperties(overrides.pageShell);
    if (props) blocks.push(`/* Precise page-shell overrides */\n.page-shell {\n${props}\n}`);
  }

  if (overrides.sections) {
    for (const [name, styles] of Object.entries(overrides.sections)) {
      const props = styleProperties(styles);
      if (props) {
        const sel = kebabCase(name);
        blocks.push(`/* Precise overrides for ${name} */\n[data-section="${sel}"] {\n${props}\n}`);
      }
    }
  }

  if (overrides.components) {
    for (const [name, styles] of Object.entries(overrides.components)) {
      const props = styleProperties(styles);
      if (props) {
        const sel = kebabCase(name);
        blocks.push(`/* Precise overrides for ${name} */\n[data-component="${sel}"] {\n${props}\n}`);
      }
    }
  }

  return blocks.length > 0 ? "\n" + blocks.join("\n\n") + "\n" : "";
}

function renderDeclaredStyles(plan) {
  const blocks = [];
  for (const section of plan.sections || []) {
    const props = styleProperties(section.styles);
    if (props) {
      blocks.push(`/* Measured styles for ${section.name} */\n[data-section="${kebabCase(section.name)}"] {\n${props}\n}`);
    }
  }
  for (const component of plan.components || []) {
    const props = styleProperties(component.styles);
    if (props) {
      blocks.push(`/* Measured styles for ${component.name} */\n[data-component="${kebabCase(component.name)}"] {\n${props}\n}`);
    }
  }
  return blocks.length > 0 ? "\n" + blocks.join("\n\n") + "\n" : "";
}

function renderBoxLayoutCss(items, scale = { x: 1, y: 1 }, options = {}) {
  if (!Array.isArray(items) || items.length === 0) return "";
  const blocks = [];
  const dataAttribute = options.dataAttribute || "section";

  for (const item of items) {
    const box = item.box || (item.styles && item.styles.box);
    const positioning = item.positioning || (item.styles && item.styles.positioning);
    if (!box || positioning !== "absolute") continue;

    const sel = kebabCase(item.name);
    const rules = [];
    const cssValue = (value, axis) => Math.round(value * scale[axis] * 10000) / 10000;
    if (box.x !== undefined) rules.push(`  left: ${cssValue(box.x, "x")}px;`);
    if (box.y !== undefined) rules.push(`  top: ${cssValue(box.y, "y")}px;`);
    if (box.width !== undefined) rules.push(`  width: ${cssValue(box.width, "x")}px;`);
    if (box.height !== undefined) rules.push(`  height: ${cssValue(box.height, "y")}px;`);

    if (rules.length > 0) {
      blocks.push(`/* Box-model layout for ${item.name} */\n[data-${dataAttribute}="${sel}"] {\n  position: absolute;\n${rules.join("\n")}\n}`);
    }
  }

  return blocks.length > 0 ? "\n" + blocks.join("\n\n") + "\n" : "";
}

function renderAllPrecisionCss(plan) {
  const declared = renderDeclaredStyles(plan);
  const overrides = renderPreciseOverrides(plan.preciseOverrides || {});
  const raster = plan.referenceRaster || plan.measurements?.referenceRaster;
  const viewport = plan.cssViewport || plan.measurements?.cssViewport;
  const rasterCoordinates = plan.coordinateSpace === "reference-raster-px";
  const scale = rasterCoordinates && raster?.width && raster?.height && viewport?.width && viewport?.height
    ? { x: viewport.width / raster.width, y: viewport.height / raster.height }
    : { x: 1, y: 1 };
  const sectionBoxLayout = renderBoxLayoutCss(plan.sections || [], scale);
  const sectionByName = new Map((plan.sections || []).map((section) => [section.name, section]));
  const components = (plan.components || []).map((component) => {
    const box = component.relativeBox || component.box;
    const parent = component.parentSection ? sectionByName.get(component.parentSection) : null;
    const parentBox = parent?.box || parent?.styles?.box;
    const resolvedBox = box && parentBox && !component.relativeBox
      ? { ...box, x: box.x - parentBox.x, y: box.y - parentBox.y }
      : box;
    return {
      ...component,
      box: resolvedBox,
      positioning: resolvedBox ? (component.positioning || "absolute") : component.positioning,
    };
  });
  const componentBoxLayout = renderBoxLayoutCss(components, scale, {
    dataAttribute: "component",
    label: "component",
  });
  return declared + overrides + sectionBoxLayout + componentBoxLayout;
}

module.exports = { pageStyles, renderDeclaredStyles, renderPreciseOverrides, renderBoxLayoutCss, renderAllPrecisionCss };
